src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @Assert\Date(message="La date d'arrivée doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui", groups={"front"})
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @Assert\Date(message="La date de départ doit être au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignéz que la date d'arrivée")
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if(empty($this->createdAt))
        {
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount))
        {
            $this->amount = $this->ad->getPrice();
        }
    }

    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDays = $this->getDays();
        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };
        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);
        foreach ($days as $day) {
            if(array_search($day, $notAvailable) !== false) return false;
        }
        return true;
    }

    public function getDays()
    {
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);
        return $days;
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Cette adresse email est déjà inscrite")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner votre prénom")
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner votre nom")
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @Assert\Email(message="Veuillez renseigner un email valide")
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @Assert\Url(message="Veuillez renseigner une URL valide")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Votre mot de passe n'est pas similaire")
     */
    private $passwordConfirm;

    /**
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caractères")
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @Assert\Length(min=50, minMessage="Votre description doit faire au moins 50 caractères")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getPasswordConfirm(): ?string
    {
        return $this->passwordConfirm;
    }

    public function setPasswordConfirm(string $passwordConfirm): self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
//        dump($roles);
//        die();
        return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingFormType;
use App\Form\CommentFormType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking.created")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $em)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingFormType::class, $booking);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)
                ->setAd($ad);
            if(!$booking->isBookableDates()) {
                $this->addFlash('warning', "Les dates que vous avez choisi ne peuvent pas être réservées, elles sont déjà prises");
            } else {
                $em->persist($booking);
                $em->flush();
                return $this->redirectToRoute('booking.show', ['id' => $booking->getId(), 'success' => true]);
            }
        }
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/booking/{id}", name="booking.show")
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $em)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentFormType::class, $comment);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());
            $em->persist($comment);
            $em->flush();
            $this->addFlash('success', "Votre ccommentaire a bien été prise en compte");
        }
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résever l'annonce {{ ad.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réserver l'annonce {{ ad.title }}</h1>
        <p>Vous etes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong></p>
        {{ form_start(form) }}
            <div class="alert alert-light">
                <h2>Renseignez vos dates</h2>
                <div class="row">
                    <div class="col">
                        {{ form_row(form.startDate) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.endDate) }}
                    </div>
                </div>
                <h4>Montant du séjour : <span id="amount">…</span> &euro;</h4>
                <span id="days">0</span> nuit(s) à {{ ad.price }} / nuit
                <h4 class="mt-3">Commentaire ?</h4>
                {{ form_row(form.comment) }}
            </div>
            <button type="submit" class="btn btn-success">Réserver</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#booking_form_startDate, #booking_form_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                        "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_form_startDate, #booking_form_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            const endDate = new Date($('#booking_form_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_form_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            if(startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};
                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}
    <div class="container">
        <h2>Votre réservation (n°{{ booking.id }}</h2>
        {% if app.request.query.get('success') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo</h4>
                <p>
                    Votre réservation auprès de <strong><a href="{{ path('user.show', {'slug': ad.slug}) }}">{{ author.fullName }}</a></strong> pour l'annonce
                    <strong><a href="{{ path('show.ads', {'slug': ad.slug}) }}">{{ ad.title }}</a></strong> a bien été prise en compte !
                </p>
            </div>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="alert alert-light">
                        <h2>Détails</h2>
                        <dl class="row">
                            <dt class="col-md-4">Numéro</dt>
                            <dd class="col-md-8">{{ booking.id }}</dd>
                            <dt class="col-md-4">Date d'arrivée</dt>
                            <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Date de départ</dt>
                            <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Nombre de nuits</dt>
                            <dd class="col-md-8">{{ booking.duration }}</dd>
                            <dt class="col-md-4">Montant total</dt>
                            <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                            <dt class="col-md-4">Commentaire</dt>
                            <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                        </dl>
                        <hr>
                        <h2 class="alert-heading">Votre hôte</h2>
                        <div class="row mb-3">
                            <div class="col-3">
                                <img src="{{ booking.ad.author.picture }}" class="avatar avatar-medium" alt="{{ author.fullName }}">
                            </div>
                            <div class="col">
                                <h4>
                                    <a href="{{ path('user.show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                                </h4>
                                <span class="badge badge-primary">{{ author.ads | length }} annonces</span>
                            </div>
                        </div>
                        {{ author.description | raw }}
                        <a href="{{ path('user.show', {'slug': author.slug}) }}" class="btn btn-primary">Plus d'info sur {{ author.firstName }}</a>
                    </div>
                    <div class="alert alert-light" id="comment">
                        <h2 class="alert-heading">Votre avis compte</h2>
                        {% if date() > date(booking.endDate) %}
                            {% set comment = booking.ad.commentFromAuthor(app.user) %}
                            {% if comment is not null %}
                                <blockquote>
                                    {{ comment.content }}
                                </blockquote>
                                <strong>Note : </strong> {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                            {% else %}
                                {{ form_start(form) }}
                                    {{ form_widget(form) }}
                                    <button type="submit" class="btn btn-success">Commenter</button>
                                {{ form_end(form) }}
                            {% endif %}
                        {% else %}
                            <p>Vous ne pourrez pas noter tant que votre séjour ne sera pas complet</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="alert alert-light">
                        <h2 class="alert-heading">Votre hébergement</h2>
                        <h4>
                            <a href="{{ path('show.ads', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                        </h4>
                        <img src="{{ ad.coverImage }}" alt="{{ ad.title }}" class="img-fluid">
                        {{ ad.content | raw }}
                        <a href="{{ path('show.ads', {'slug': ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    Réservation (n°{{ booking.id }})
{% endblock %}