src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"title"}, message="Ce titre existe déjà")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=10, max="255", minMessage="Le titre est trop court. 10 carctères mini", maxMessage="Le titre est trop log")
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @Assert\Length(min=10, minMessage="L'intro est trop court. 10 carctères mini")
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @Assert\Length(min=10, minMessage="Le contenu est trop court. 10 carctères mini")
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Assert\Url()
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @Assert\Valid()
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getTitle());
        }
    }

    public function getAvgRatings()
    {
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);
        if(count($this->comments) > 0)
            return $sum / count($this->comments);

        return 0;
    }

    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if($comment->getAuthor() === $author)
                return $comment;

            return null;
        }
    }

    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking) {
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $result);
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Cette adresse email est déjà inscrite")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner votre prénom")
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner votre nom")
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @Assert\Email(message="Veuillez renseigner un email valide")
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @Assert\Url(message="Veuillez renseigner une URL valide")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Votre mot de passe n'est pas similaire")
     */
    private $passwordConfirm;

    /**
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caractères")
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @Assert\Length(min=50, minMessage="Votre description doit faire au moins 50 caractères")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getPasswordConfirm(): ?string
    {
        return $this->passwordConfirm;
    }

    public function setPasswordConfirm(string $passwordConfirm): self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
//        dump($roles);
//        die();
        return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{% set url = path('show.ads', {'slug': ad.slug}) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price }}&euro; / nuit</strong><br>
            {% if ad.comments | length %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Non noté</small>
            {% endif %}
        </div>
        <img src="{{ ad.coverImage }}" alt="nom" style="height: 200px; width: 100%; display: block">
        <div class="card-body">
            <h4 class="card-title">{{ ad.title }}</h4>
            <p class="card-text">{{ ad.introduction }}</p>
            <a href="{{ url }}" class="btn btn-secondary">Voir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads.edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_form_images_widget %}
    <p>Ajouter des photos</p>
    <input type="hidden" id="widgets-counter" value="0">
    {{ form_widget(form) }}
    <div class="form-group">
        <button type="button" id="add-img" class="btn btn-primary">Ajouter</button>
    </div>
{% endblock %}

{% block _ad_form_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_form_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Création d'une annonce
{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Créer uune nouvelle annonce</h1>
        {{ form_start(form) }}
            {{ form_widget(form) }}
            <p>
                <input type="submit" class="btn btn-primary" value="Créer"> | <a href="{{ path('index.ads') }}">Cancel</a>
            </p>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset("js/ad.js") }}"></script>
{% endblock %}
{#

{% block form_row %}
#}
{#    {{ dump() }}#}{#

    <div class="form-group">
        {{ form_label(form) }}
        {{ form_widget(form) }}
    </div>
{% endblock %}

{% block text_widget %}
    <input type="text" name="{{ full_name }}" id="{{ id }}" class="form-control">
{% endblock %}
#}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Modifier l'annonce {{ ad.title }}</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <p>
            <input type="submit" class="btn btn-primary" value="Modifier"> | <a href="{{ path('index.ads') }}">Cancel</a>
        </p>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block title %}
    Edition de l'annonce {{ ad.title }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset("js/ad.js") }}"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-3">Voici les annonces</h1>
        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ad.title }}{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.introduction }}</p>
        <p class="h2">
            <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price }}&euro;</strong> par nuit
        </p>
        <a href="{{ path('booking.created', {'slug': ad.slug}) }}" class="btn btn-primary">Réserver</a>
        {% if app.user and app.user == ad.author %}
            <a href="{{ path('ads.edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier</a>
            <a href="{{ path('ads.delete', {'slug': ad.slug}) }}" class="btn btn-danger" onclick="return confirm(`Etes vous sur : {ad.title} ?`)">Supprimer</a>
        {% endif %}
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw }}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">`
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img src="{{ image.url }}" class="d-block w-100" alt="first">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <hr>
                {% if ad.comments | length %}
                    <h2 class="mb-3">Commentaires :</h2>
                    <div class="alert alert-info">
                        <h4 class="alert-heading">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note globale
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                                    <br>
                                    <small>Calculée sur {{ ad.comments | length }} avis</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light mb-3 rounded py-3 px-3">
                            <strong>{{ comment.author.firstName }}</strong> a dit :
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note donnée : </strong>{{ comment.rating }}
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h4>Cette annonce n'a pas encore de commentaires</h4>
                {% endif %}
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row mb-3">
                    <div class="col-3">
                        <a href="{{ path('user.show', {'slug': a.slug}) }}">
                            <img src="{{ a.picture }}" class="avatar avatar-medium" alt="Avatar {{ a.fullName }}">
                        </a>
                    </div>
                    <div class="col">
                        <a href="{{ path('user.show', {'slug': a.slug}) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.ads | length }} annonces</span>
                    </div>
                </div>
                {{ a.description | raw }}
            </div>
        </div>
    </div>
{% endblock %}